In [ ]:
import pandas as pd
import numpy as np
import yfinance as yf
import matplotlib.pyplot as plt 
import plotly_express as px 
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score

In [2]:
data = yf.download("AAPL", start='2020-01-01', end='2026-04-17')

[*********************100%***********************]  1 of 1 completed

In [3]:
data.head()

Price           Close       High        Low       Open     Volume
Ticker           AAPL       AAPL       AAPL       AAPL       AAPL
Date
2020-01-02  72.400520  72.460784  71.156682  71.409785  135480400
2020-01-03  71.696648  72.455966  71.472469  71.629153  146322800
2020-01-06  72.267952  72.306521  70.568525  70.819223  118387200
2020-01-07  71.928024  72.533064  71.708665  72.277548  108872000
2020-01-08  73.085121  73.386438  71.631567  71.631567  132079200

In [4]:
data.columns = data.columns.droplevel(1)

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 1580 entries, 2020-01-02 to 2026-04-16
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Close   1580 non-null   float64
 1   High    1580 non-null   float64
 2   Low     1580 non-null   float64
 3   Open    1580 non-null   float64
 4   Volume  1580 non-null   int64
dtypes: float64(4), int64(1)
memory usage: 74.1 KB

In [6]:
# Calculating Price Change
data['Price_Change'] = data['Close'].diff()
data['pct_change'] = data['Close'].pct_change() * 100
data.fillna(0,inplace=True)
data.head(5)

Price,Close,High,Low,Open,Volume,Price_Change,pct_change
Date,,,,,,,
2020-01-02,72.400520,72.460784,71.156682,71.409785,135480400,0.000000,0.000000
2020-01-03,71.696648,72.455966,71.472469,71.629153,146322800,-0.703873,-0.972193
2020-01-06,72.267952,72.306521,70.568525,70.819223,118387200,0.571304,0.796835
2020-01-07,71.928024,72.533064,71.708665,72.277548,108872000,-0.339928,-0.470371
2020-01-08,73.085121,73.386438,71.631567,71.631567,132079200,1.157097,1.608687

In [7]:
data.columns

Index(['Close', 'High', 'Low', 'Open', 'Volume', 'Price_Change', 'pct_change'], dtype='object', name='Price')

In [8]:
# Seprating Gain and loss
data["Gain"] = data["Price_Change"].clip(lower=0)
data["Loss"] = -data["Price_Change"].clip(upper=0)

In [9]:
# Rolling Average
data['Avg_Gain'] = data['Gain'].rolling(5).mean()
data['Avg_Loss'] = data['Loss'].rolling(5).mean()

In [10]:
# Relative Strength
data['RS'] = data['Avg_Gain'] / data['Avg_Loss']

In [11]:
# RSI 
data['RSI'] = 100 - (100/(1 + data['RS']))

In [12]:
# Signal
data["Signal"] = "HOLD"
data.loc[(data["RSI"] < 30) & (data["RSI"].shift(1) >= 30), "Signal"] = "BUY"
data.loc[(data["RSI"] > 70) & (data["RSI"].shift(1) <= 70), "Signal"] = "SELL"

In [13]:
data.dropna(inplace=True)

In [14]:
data.head(21)

Price,Close,High,Low,Open,Volume,Price_Change,pct_change,Gain,Loss,Avg_Gain,Avg_Loss,RS,RSI,Signal
Date,,,,,,,,,,,,,,
2020-01-08,73.085121,73.386438,71.631567,71.631567,132079200,1.157097,1.608687,1.157097,-0.000000,0.345680,0.208760,1.655873,62.347602,HOLD
2020-01-09,74.637512,74.830352,73.810699,74.061390,170108400,1.552391,2.124086,1.552391,-0.000000,0.656158,0.208760,3.143122,75.863614,SELL
2020-01-10,74.806244,75.370316,74.304855,74.871333,140644800,0.168732,0.226068,0.168732,-0.000000,0.689905,0.067986,10.147817,91.029634,HOLD
2020-01-13,76.404396,76.430916,75.003874,75.121996,121532000,1.598152,2.136389,1.598152,-0.000000,0.895274,0.067986,13.168601,92.942140,HOLD
2020-01-14,75.372719,76.551476,75.249786,76.341760,161954400,-1.031677,-1.350285,0.000000,1.031677,0.895274,0.206335,4.338927,81.269643,HOLD
2020-01-15,75.049683,76.052467,74.618194,75.172622,121923600,-0.323036,-0.428585,0.000000,0.323036,0.663855,0.270943,2.450168,71.015900,HOLD
2020-01-16,75.989807,76.100697,75.230489,75.592070,108829200,0.940125,1.252670,0.940125,-0.000000,0.541402,0.270943,1.998215,66.646819,HOLD
2020-01-17,76.831100,76.833506,75.931967,76.238103,137816400,0.841293,1.107113,0.841293,-0.000000,0.675914,0.270943,2.494675,71.385037,SELL
2020-01-21,76.310410,76.900987,76.173007,76.459862,110843200,-0.520691,-0.677709,0.000000,0.520691,0.356284,0.375081,0.949885,48.714915,HOLD
2020-01-22,76.582794,77.134802,76.488780,76.794915,101832400,0.272385,0.356943,0.272385,-0.000000,0.410760,0.168745,2.434202,70.881156,SELL
2020-01-23,76.951599,77.031144,76.088622,76.635819,104472000,0.368805,0.481577,0.368805,-0.000000,0.484521,0.104138,4.652678,82.309272,HOLD
2020-01-24,76.729874,77.939962,76.539439,77.197519,146537600,-0.221725,-0.288136,0.000000,0.221725,0.296497,0.148483,1.996835,66.631461,HOLD
2020-01-27,74.473564,75.153330,73.492474,74.741130,161940000,-2.256310,-2.940588,0.000000,2.256310,0.128238,0.599745,0.213821,17.615507,BUY
2020-01-28,76.580406,76.751552,75.254610,75.353443,162234000,2.106842,2.828980,2.106842,-0.000000,0.549606,0.495607,1.108956,52.583173,HOLD
2020-01-29,78.183403,79.029504,77.469886,78.209923,216229200,1.602997,2.093221,1.602997,-0.000000,0.815729,0.495607,1.645919,62.205942,HOLD
2020-01-30,78.070099,78.123131,76.835905,77.267393,126743200,-0.113304,-0.144921,0.000000,0.113304,0.741968,0.518268,1.431630,58.875323,HOLD
2020-01-31,74.608566,77.783241,74.314480,77.361397,199588400,-3.461533,-4.433878,0.000000,3.461533,0.741968,1.166229,0.636211,38.883185,HOLD
2020-02-03,74.403664,75.567950,72.851277,73.352665,173788400,-0.204903,-0.274637,0.000000,0.204903,0.741968,0.755948,0.981507,49.533348,HOLD
2020-02-04,76.860031,77.050466,75.601730,76.006698,136616400,2.456367,3.301407,2.456367,-0.000000,0.811873,0.755948,1.073980,51.783526,HOLD
2020-02-05,77.486755,78.284643,76.884121,77.985731,118826800,0.626724,0.815410,0.626724,-0.000000,0.616618,0.755948,0.815689,44.924488,HOLD
2020-02-06,78.393120,78.395533,77.199908,77.756741,105425600,0.906364,1.169702,0.906364,-0.000000,0.797891,0.733287,1.088102,52.109623,HOLD

In [15]:
data["Target"] = np.where(data["Close"].shift(-1) > data["Close"], "BUY", "SELL")

In [16]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()
Y = le.fit_transform(data["Target"])

In [17]:
features = ["RSI", "Avg_Gain", "Avg_Loss", "Price_Change", "pct_change"]

X = data[features]
Y = data["Target"]

In [18]:
# Train test Split 
split = int(len(data)*0.8)

X_train = X[:split]
X_test = X[split:]

Y_train = Y[:split]
Y_test = Y[split:]

In [19]:
# Scaling
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [27]:
# LogisticRegression 
model_lr = LogisticRegression()
model_lr.fit(X_train,Y_train)

# Prediction
y_pred_lr = model_lr.predict(X_test)

# Accuracy Check
print('Accutacy :', accuracy_score(Y_test,y_pred_lr))

result = pd.DataFrame({
    'Actual': Y_test,
    'Prediction': y_pred_lr
})
result.head()

Accutacy : 0.5158227848101266

           Actual Prediction
Date
2025-01-13   SELL       SELL
2025-01-14    BUY        BUY
2025-01-15   SELL        BUY
2025-01-16    BUY       SELL
2025-01-17   SELL        BUY

In [32]:
# RandomForestClassifier
model_rf = RandomForestClassifier()
model_rf.fit(X_train,Y_train)

#Prediction
y_pred_rf = model_lr.predict(X_test)

#Accuracy check
print('accuracy_score :', accuracy_score(Y_test,y_pred_rf))

#Prediction check
result_rf = pd.DataFrame({
    'Actual':Y_test,
    'Predicted':y_pred_rf
})
result_rf.head()

accuracy_score : 0.5158227848101266

           Actual Predicted
Date
2025-01-13   SELL      SELL
2025-01-14    BUY       BUY
2025-01-15   SELL       BUY
2025-01-16    BUY      SELL
2025-01-17   SELL       BUY

In [21]:
data.head()

Price,Close,High,Low,Open,Volume,Price_Change,pct_change,Gain,Loss,Avg_Gain,Avg_Loss,RS,RSI,Signal,Target
Date,,,,,,,,,,,,,,,
2020-01-08,73.085121,73.386438,71.631567,71.631567,132079200,1.157097,1.608687,1.157097,-0.000000,0.345680,0.208760,1.655873,62.347602,HOLD,BUY
2020-01-09,74.637512,74.830352,73.810699,74.061390,170108400,1.552391,2.124086,1.552391,-0.000000,0.656158,0.208760,3.143122,75.863614,SELL,BUY
2020-01-10,74.806244,75.370316,74.304855,74.871333,140644800,0.168732,0.226068,0.168732,-0.000000,0.689905,0.067986,10.147817,91.029634,HOLD,BUY
2020-01-13,76.404396,76.430916,75.003874,75.121996,121532000,1.598152,2.136389,1.598152,-0.000000,0.895274,0.067986,13.168601,92.942140,HOLD,SELL
2020-01-14,75.372719,76.551476,75.249786,76.341760,161954400,-1.031677,-1.350285,0.000000,1.031677,0.895274,0.206335,4.338927,81.269643,HOLD,SELL

In [23]:
X_test = pd.DataFrame(X_test, index=Y_test.index)

In [24]:
data.loc[X_test.index, 'ML_Signal'] = y_pred_lr

In [25]:
def final_signal(row):
    if row['Signal'] == 'BUY' and row['ML_Signal'] == 'BUY':
        return 'STRONG BUY'
    
    elif row['Signal'] == 'SELL' and row['ML_Signal'] == 'SELL':
        return 'STRONG SELL'
    
    elif row['ML_Signal'] == 'BUY':
        return 'WEAK BUY'
    
    elif row['ML_Signal'] == 'SELL':
        return 'WEAK SELL'
    
    else:
        return 'HOLD'
    
data['Final_Signal'] = data.apply(final_signal, axis = 1)